-- 완료된 중고 거래의 총금액이 70만 원 이상인 사람의 회원 ID, 닉네임, 총거래금액을 조회
SELECT
    USER_ID, NICKNAME, SUM(PRICE) AS TOTAL_SALES
FROM
    USED_GOODS_BOARD AS B, USED_GOODS_USER AS U
WHERE
    B.WRITER_ID = U.USER_ID AND
    STATUS = 'DONE'
GROUP BY USER_ID
HAVING TOTAL_SALES >= 700000
ORDER BY TOTAL_SALES;

