SELECT
    B.BOOK_ID,
    A.AUTHOR_NAME,
    DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM
    AUTHOR AS A
LEFT JOIN
    BOOK AS B ON A.AUTHOR_ID = B.AUTHOR_ID
WHERE
    B.CATEGORY LIKE '경제'
ORDER BY PUBLISHED_DATE;

